### PR TITLE
Fix Www-Authenticate not being read

### LINKED ISSUE #884: [Bug] AzureArcManagedIdentitySource looking for WWW-Authenticate response header while agent returns Www-Authenticate
### Library version used

1.17.2

### Java version

21

### Scenario

Other - please specify

### Is this a new or an existing app?

This is a new app or experiment

### Issue description and reproduction steps

I am trying to log in my application running on an Azure Arc enabled Ubuntu 24.04 server. In the class AzureArcManagedIdentitySource, there is a check for existence of the WWW-Authenticate header. However, my agent returns the header without capitals: Www-Authenticate (see image).

image

I see the code used to check for Www-Authenticate but this changed with this commit: https://github.com/AzureAD/microsoft-authentication-library-for-java/commit/68bba5168b61726afd8ca223e70a54062ad09c01

### Relevant code snippets

_No response_

### Expected behavior

I expect my application to log in via the Azure Arc Managed Identity.

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

### Regression

1.15.0

### Solution and workarounds

I assume best option would be to make the check case-insensitive...

### PR DESCRIPTION
**Pull request by blancqua**
Fixes https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/884

### CODE REVIEW

**Comment by blancqua** [comment]
@microsoft-github-policy-service agree

File: msal4j-sdk/src/main/java/com/microsoft/aad/msal4j/AzureArcManagedIdentitySource.java [hunk 1]
```diff
@@ -150,6 +150,16 @@ public ManagedIdentityResponse handleResponse(
         return super.handleResponse(parameters, response);
     }
 
+    private Optional<String> readChallengeFrom(IHttpResponse response) {
+        return response.headers()
+                .entrySet()
+                .stream()
+                .filter(entry -> WWW_AUTHENTICATE_HEADER.equalsIgnoreCase(entry.getKey()))
```
Comment (bgavrilMS) [inline msal4j-sdk/src/main/java/com/microsoft/aad/msal4j/AzureArcManagedIdentitySource.java:157]: I think this warrants a unit test, just updating the existing one from here https://github.com/AzureAD/microsoft-authentication-library-for-java/commit/68bba5168b61726afd8ca223e70a54062ad09c01#diff-c1e78d16db8b6cb86ef4e37c4f14c7950221b0fd619b2ab501499c588b5c0833R620

**Review by bgavrilMS — COMMENTED** [review]
LGTM, just needs a small unit test. 

Thanks so much @blancqua

File: msal4j-sdk/src/main/java/com/microsoft/aad/msal4j/AzureArcManagedIdentitySource.java (hunk 1 above)
Comment (blancqua) [reply msal4j-sdk/src/main/java/com/microsoft/aad/msal4j/AzureArcManagedIdentitySource.java:157]: Hi @bgavrilMS ! I extended the existing tests to run with both variations of the header key. Slipped in some small refactor as well to avoid duplication, hope you don't mind.

**Comment by blancqua** [comment]
Hi @bgavrilMS ! I extended the existing tests to run with both variations of the header key. Slipped in some small refactor as well to avoid duplication, hope you don't mind.

**Review by bgavrilMS — APPROVED** [review]

**Review by Avery-Dunn — APPROVED** [review]
Looks good to me, thanks for the help with this!

**Comment by blancqua** [comment]
Thanks, any clue when there might be a release including this?
